### PR TITLE
Fix Color Picker Collaboration Bug

### LINKED ISSUE #18: Color Picker Breaks with Remote Edits
The color picker example edits the incorrect location in a context where the document is modified during the interaction. Here's a video clip of what happens:

https://github.com/replit/codemirror-interact/assets/68416/4a842178-8b77-46a7-bcf3-ff0c0c0ad6d6

I tried this, which seems to solve it.

```js
if (this.target.rule.onClick) {
  this.target.rule.onClick(
    this.target.text,
    // Old - doesn't work due to using stale target
    // this.updateText(this.target),
    // New - works because it uses the latest target
    (text) => {
      this.target && this.updateText(this.target)(text);
    },
    e
  );
}
```

After that change:

https://github.com/replit/codemirror-interact/assets/68416/39900a95-fd05-4b30-9f77-6a27c62399d1

### PR DESCRIPTION
**Pull request by curran**
Closes #18

Before: 

https://github.com/replit/codemirror-interact/assets/68416/4a842178-8b77-46a7-bcf3-ff0c0c0ad6d6

After:

https://github.com/replit/codemirror-interact/assets/68416/39900a95-fd05-4b30-9f77-6a27c62399d1

### CODE REVIEW

**Comment by curran** [comment]
Any thoughts on this PR?

Hey just a heads up I'm considering setting up an active fork of this repo.

**Review by sergeichestakov — APPROVED** [review]
looks good, thanks for the fix! 🙏

**Comment by sergeichestakov** [comment]
and no problem feel free to fork or keep submitting PRs. we're not actively adding new features to this project but I am still keeping an eye on it and accepting PRs. thanks for your patience!

**Comment by curran** [comment]
Thanks a ton!

**Pull request merged**
